[package]
authors = ["Ryan Brewster"]
description = "Rust crate for compiling CEL"
name = "wasm-cel"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = "^1.0"
serde_json = "^1.0"
wasm-bindgen = "0.2.25"
